# Generated by Django 3.0.6 on 2020-05-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tesco_password',
            field=models.CharField(max_length=200),
        ),
    ]
